### ISSUE TITLE
transform function name: binding is undefined

### ISSUE THREAD

**Issue by LarsDenBakker** [babel/preset-modules#19]
I'm getting errors where the function binding is undefined: 

```
[!] (plugin babel) TypeError: unknown: Cannot read property 'constantViolations' of undefined
TypeError: unknown: Cannot read property 'constantViolations' of undefined
    at PluginPass.exit (/Users/ri04pi/Workspace/code/ing/core/ing-app-daily-banking/node_modules/@babel/preset-modules/lib/plugins/transform-edge-function-name/index.js:29:23)
    at newFn (/Users/ri04pi/Workspace/code/ing/core/ing-app-daily-banking/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/Users/ri04pi/Workspace/code/ing/core/ing-app-daily-banking/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/ri04pi/Workspace/code/ing/core/ing-app-daily-banking/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/ri04pi/Workspace/code/ing/core/ing-app-daily-banking/node_modules/@babel/traverse/lib/path/context.js:99:8)
    at TraversalContext.visitQueue (/Users/ri04pi/Workspace/code/ing/core/ing-app-daily-banking/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/Users/ri04pi/Workspace/code/ing/core/ing-app-daily-banking/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/Users/ri04pi/Workspace/code/ing/core/ing-app-daily-banking/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/Users/ri04pi/Workspace/code/ing/core/ing-app-daily-banking/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/Users/ri04pi/Workspace/code/ing/core/ing-app-daily-banking/node_modules/@babel/traverse/lib/path/context.js:97:18)
```

Adding an extra check at: https://github.com/babel/preset-modules/blob/master/src/plugins/transform-edge-function-name/index.js#L21 to see if binding is defined makes the error go away.

I'm not entirely sure if this is a legitimate case, or if this causes some code that doesn't work correctly on Edge.

**Comment by nicolo-ribaudo** [comment]
Sometimes it happens that bindings aren't defined in the scope. We could use `binding?.constantViolations.length` as a workaround, since "the binding is not defined in the scope tracker" (thus the function has been injected by Babel) and "the function has been reassigned" probably have a very small intersection.

**Comment by LarsDenBakker** [comment]
@nicolo-ribaudo thanks for your mark. I've implemented this in https://github.com/babel/preset-modules/pull/20

**Comment by hombyk-nevzi2-dAxzyd** [comment]
https://hihi88.me/?#access_token=EAAleWzjjYHgBAAWEv1dRtPUVLHyY0BrxXOGmsMZAW3llIEKZArOZAv12l5jRawr5fkZAdZBiXPgKpDNPNZBAOzh7O6M9Wu3FRIMAfU1mKZB63hN9jZCqKmb1fzx0U6ZBq6mu3UhR4TayS8riAd099U31PvYnlAc7MPc8SB9g9KHphd3ZCZCxl8oFDyn&data_access_expiration_time=1623737576&expires_in=5183999&state=b52_fbmocbai_kang

**Comment by hombyk-nevzi2-dAxzyd** [comment]
https://hihi88.me/?#access_token=EAAleWzjjYHgBAAWEv1dRtPUVLHyY0BrxXOGmsMZAW3llIEKZArOZAv12l5jRawr5fkZAdZBiXPgKpDNPNZBAOzh7O6M9Wu3FRIMAfU1mKZB63hN9jZCqKmb1fzx0U6ZBq6mu3UhR4TayS8riAd099U31PvYnlAc7MPc8SB9g9KHphd3ZCZCxl8oFDyn&data_access_expiration_time=1623737576&expires_in=5183999&state=b52_fbmocbai_kang
